name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker compose down --volumes --remove-orphans || true

      - run: |
          cat <<EOF > .env
          DATABASE_ROOT_PASSWORD=${{ secrets.DATABASE_ROOT_PASSWORD }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          WALLET_TRACKER_SECRET=${{ secrets.WALLET_TRACKER_SECRET }}
          WALLET_TRACKER_DB_USER=${{ secrets.WALLET_TRACKER_DB_USER }}
          WALLET_TRACKER_DB_HOST=db
          EOF

      - run: docker compose up -d --build

      - run: |
          echo "Waiting for database to be ready..."
          for i in {1..30}; do
            if docker compose exec -T db sh -c 'mariadb -uroot -p"$DATABASE_ROOT_PASSWORD" -e "SELECT 1;" >/dev/null 2>&1'; then
              echo "Database is up!"
              break
            fi
            echo "Waiting for database..."
            sleep 2
          done


      - run: docker compose exec -T app pytest -v

      - if: always()
        run: docker compose down --volumes

